export const feedbacks = [
    {
        id: 1,
        name: "Maria Clara",
        handle: "@mariaclara_design",
        avatar: "MC",
        date: "Mar 12, 2024",
        text: "Entrei insegura nos orçamentos e saindo sem saber cobrar. Com o Kit Defesa aprendi que não é o preço que afasta cliente, é a falta de estrutura. Fechei três projetos em duas semanas.",
    },
    {
        id: 2,
        name: "Pedro Alves",
        handle: "@pedro.criativo",
        avatar: "PA",
        date: "Mar 15, 2024",
        text: "O contrato de prestação de serviço me salvou numa situação que ia me custar R$ 2.800. Cliente quis dar marcha ré depois de aprovado. Não teve como, estava tudo assinado.",
    },
    {
        id: 3,
        name: "Juliana Mendes",
        handle: "@juni.identidade",
        avatar: "JM",
        date: "Mar 17, 2024",
        text: "A planilha de fluxo de caixa me mostrou que eu estava trabalhando 60h por semana e sendo paga como se trabalhasse 20. Reajustei tudo. Hoje ganho mais trabalhando menos.",
    },
    {
        id: 4,
        name: "Thiago Costa",
        handle: "@thiagocosta.branding",
        avatar: "TC",
        date: "Mar 19, 2024",
        text: "Usava tabela do Word pra montar proposta. Hoje mando a proposta profissional do kit e o cliente já para na hora de questionar o valor. Visual muda o jogo completamente.",
    },
    {
        id: 5,
        name: "Camila Ramos",
        handle: "@camilaramos.ux",
        avatar: "CR",
        date: "Mar 20, 2024",
        text: "O briefing foi a virada de chave pra mim. Antes eu ia em reunião sem roteiro e saía sem saber o que fazer. Agora tenho clareza desde o primeiro contato e o cliente percebe isso.",
    },
    {
        id: 6,
        name: "Rodrigo Lima",
        handle: "@rodrigolima.social",
        avatar: "RL",
        date: "Mar 22, 2024",
        text: "Cliente sumiu depois de aprovar tudo. Recibo profissional me deu prova do pagamento parcial. Resolvi sem advogado, sem drama. Só com o documento do kit na mão.",
    },
    {
        id: 7,
        name: "Fernanda Souza",
        handle: "@fer.branddesign",
        avatar: "FS",
        date: "Mar 24, 2024",
        text: "Comecei a usar a calculadora de precificação e tive um choque do bem. Estava cobrando quase metade do que deveria. Hoje faço projetos menores e ganho mais. Inacreditável.",
    },
    {
        id: 8,
        name: "Lucas Andrade",
        handle: "@lucasandrade.id",
        avatar: "LA",
        date: "Mar 25, 2024",
        text: "Recomendo pra qualquer freelancer que ainda manda orçamento no direct. Esse kit tem a estrutura que leva anos pra montar por conta própria. Compensa demais.",
    },
];
